services:
  nginx:
    container_name: nginx-tunel
    # build: .  # 如果需要构建镜像时取消注释
    image: rebecca554owen/tunnel:latest  # 使用预构建的镜像，如果需要用本地 Dockerfile 构建则取消上面build的注释
    network_mode: host  # 使用 host 网络模式
    environment:
      - MODE=in  # 或 out
      - LISTEN_PORT=10000
      - PROXY_PASS_TARGET=127.0.0.1
      - PROXY_PASS_PORT=8080
