name: build-openppp2-env3-jemalloc

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag,默认为jemalloc'
        required: false
        default: 'jemalloc'

env:
  REGISTRY_GHCR: ghcr.io
  REGISTRY_DOCKERHUB: docker.io
  IMAGE_NAME: ${{ github.repository_owner }}/openppp2
  BOOST_VERSION: 1.86.0   # 设置默认的Boost版本
  JEMALLOC_VERSION: 5.3.0 # 设置默认的jemalloc版本
  OPENSSL_VERSION: 3.4.0  # 设置默认的OpenSSL版本

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [linux/amd64, linux/arm64]
        include:
          - platform: linux/amd64
            platform_name: linux-amd64
          - platform: linux/arm64
            platform_name: linux-arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_GHCR }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get tag
        id: get_tag
        run: |
          if [ -z "${{ github.event.inputs.tag }}" ]; then
            TAG="jemalloc"
          else
            TAG=${{ github.event.inputs.tag }}
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Validate Docker tag
        run: |
          TAG=${{ steps.get_tag.outputs.tag }}
          if ! echo "$TAG" | grep -qE '^[a-zA-Z0-9_][a-zA-Z0-9_.-]{0,127}$'; then
            echo "::error::Invalid Docker tag: $TAG"
            echo "Docker tag must match regex: [a-zA-Z0-9_][a-zA-Z0-9_.-]{0,127}"
            exit 1
          fi

      - name: Build and push platform-specific images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./openppp/base.Dockerfile
          push: true
          platforms: ${{ matrix.platform }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.REGISTRY_DOCKERHUB }}/${{ env.IMAGE_NAME }}:${{ steps.get_tag.outputs.tag }}
            ${{ env.REGISTRY_GHCR }}/${{ env.IMAGE_NAME }}:${{ steps.get_tag.outputs.tag }}
          build-args: |
            BOOST_VERSION=${{ env.BOOST_VERSION }}
            JEMALLOC_VERSION=${{ env.JEMALLOC_VERSION }}
            OPENSSL_VERSION=${{ env.OPENSSL_VERSION }}

      - name: Save digest
        shell: bash
        run: |
          mkdir -p /tmp/digests
          DIGEST=$(docker buildx imagetools inspect ${{ env.REGISTRY_DOCKERHUB }}/${{ env.IMAGE_NAME }}:${{ steps.get_tag.outputs.tag }} --format '{{json .Manifest.Digest}}')
          echo $DIGEST > /tmp/digests/${{ matrix.platform_name }}
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled

      - name: Upload digests
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.platform_name }}
          path: /tmp/digests
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          pattern: digests-*
          path: /tmp/digests
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY_DOCKERHUB }}/${{ env.IMAGE_NAME }}
            ${{ env.REGISTRY_GHCR }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ github.event.inputs.tag }}
            type=raw,value=jemalloc

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_GHCR }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          DOCKER_TAGS=$(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON")
          
          DIGEST_AMD64=$(cat linux-amd64 | tr -d '"')
          DIGEST_ARM64=$(cat linux-arm64 | tr -d '"')
          
          docker buildx imagetools create $DOCKER_TAGS \
            ${{ env.REGISTRY_DOCKERHUB }}/${{ env.IMAGE_NAME }}@$DIGEST_AMD64 \
            ${{ env.REGISTRY_DOCKERHUB }}/${{ env.IMAGE_NAME }}@$DIGEST_ARM64
          
          docker buildx imagetools create $DOCKER_TAGS \
            ${{ env.REGISTRY_GHCR }}/${{ env.IMAGE_NAME }}@$DIGEST_AMD64 \
            ${{ env.REGISTRY_GHCR }}/${{ env.IMAGE_NAME }}@$DIGEST_ARM64
            
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_DOCKERHUB }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}
          docker buildx imagetools inspect ${{ env.REGISTRY_GHCR }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}

